steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', '.']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdk-platform/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION' # Replace with your region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Only for testing! Remove for production.
      - '--set-env-vars' # setting env variable
      - 'GCS_BUCKET_NAME=$_GCS_BUCKET_NAME'

# Substitutions (variables)
substitutions:
  _SERVICE_NAME: simple-app # Replace with your service name
  _REGION: us-central1 # Replace with your region
  _GCS_BUCKET_NAME: bestie-app # Replace with your bucket name

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'